///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsTajawalBlack = 'assets/fonts/Tajawal-Black.ttf';
  static const String fontsTajawalBold = 'assets/fonts/Tajawal-Bold.ttf';
  static const String fontsTajawalExtraBold =
      'assets/fonts/Tajawal-ExtraBold.ttf';
  static const String fontsTajawalExtraLight =
      'assets/fonts/Tajawal-ExtraLight.ttf';
  static const String fontsTajawalLight = 'assets/fonts/Tajawal-Light.ttf';
  static const String fontsTajawalMedium = 'assets/fonts/Tajawal-Medium.ttf';
  static const String fontsTajawalRegular = 'assets/fonts/Tajawal-Regular.ttf';
  static const String iconsAccountCircleNavBar =
      'assets/icons/accountCircleNavBar.svg';
  static const String iconsAcute = 'assets/icons/acute.svg';
  static const String iconsAddBoxNavBar = 'assets/icons/addBoxNavBar.svg';
  static const String iconsAddToCart = 'assets/icons/AddToCart.svg';
  static const String iconsCars = 'assets/icons/cars.svg';
  static const String iconsChatNavBar = 'assets/icons/chatNavBar.svg';
  static const String iconsCompanyBadge = 'assets/icons/CompanyBadge.svg';
  static const String iconsFavorite = 'assets/icons/favorite.svg';
  static const String iconsGlobe = 'assets/icons/globe.svg';
  static const String iconsHomeNavBar = 'assets/icons/homeNavBar.svg';
  static const String iconsKeep = 'assets/icons/keep.svg';
  static const String iconsLocalFireDepartment =
      'assets/icons/local_fire_department.svg';
  static const String iconsLocationOn = 'assets/icons/location_on.svg';
  static const String iconsMyAdsNavBar = 'assets/icons/myAdsNavBar.svg';
  static const String iconsOffer = 'assets/icons/offer.svg';
  static const String iconsRocket = 'assets/icons/rocket.svg';
  static const String iconsTmg = 'assets/icons/tmg.jpg';
  static const String iconsTtt = 'assets/icons/ttt.svg';
  static const String iconsWorkspacePremium =
      'assets/icons/workspace_premium.svg';
  static const String imagesAccessories = 'assets/images/accessories.png';
  static const String imagesMan = 'assets/images/man.png';
  static const String imagesPhone = 'assets/images/phone.png';
  static const String imagesProduct1 = 'assets/images/product1.png';
  static const String imagesProduct2 = 'assets/images/product2.png';
  static const String imagesProduct3 = 'assets/images/product3.png';
  static const String imagesProduct4 = 'assets/images/product4.png';
  static const String imagesProduct5 = 'assets/images/product5.png';
  static const String imagesProduct6 = 'assets/images/product6.png';
  static const String imagesProduct7 = 'assets/images/product7.png';
  static const String imagesProduct8 = 'assets/images/product8.png';
  static const String imagesRectangle = 'assets/images/Rectangle .svg';
  static const String imagesWatch = 'assets/images/watch.png';
}
